#pragma once

#define ROBOT_WIFI_SSID "YOUR_WIFI_SSID"
#define ROBOT_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define ROBOT_MCP_URI "ws://YOUR_MCP_SERVER_IP:8080/esp32_ws"
#define ROBOT_DEVICE_ID "ESP32_KORVO_2"

#define ROBOT_AUDIO_SAMPLE_RATE 16000
#define ROBOT_AUDIO_BITS 16
#define ROBOT_AUDIO_CHANNELS 1
